svc_base_uri: scratch.ns/services
poll_interval: 5m
metadata:
  s.vtemp:
    SourceName: "Virtual Temperature Sensor"
  s.vtemp/vtemp_sensor/i.xbox.temperature_sensor/signal/temperature:
    UnitofMeasure: Farenheight
    Type: Temperature