svc_base_uri: <base uri of service>
entityfile: <relative path to entity file>
URL: http://<your ip:port here>/api/LiveData.xml
extract: 
    - MTU1
    - MTU2
name: main
poll_interval: 1s
metadata:
    s.TED:
        SourceName: "TED Main"
    s.TED/MTU1:
        Kind: Load
    s.TED/MTU2:
        Kind: Supply
    s.TED/MTU1/i.meter/signal/Voltage:
        UnitofMeasure: V
    s.TED/MTU1/i.meter/signal/PowerNow:
        UnitofMeasure: kW
    s.TED/MTU1/i.meter/signal/KVA:
        UnitofMeasure: kVA

    s.TED/MTU2/i.meter/signal/Voltage:
        UnitofMeasure: V
    s.TED/MTU2/i.meter/signal/PowerNow:
        UnitofMeasure: kW
    s.TED/MTU2/i.meter/signal/KVA:
        UnitofMeasure: kVA

