svc_base_uri: scratch.ns/devices/ketimotes
entityfile: entity.ent
SerialPorts:
- /dev/ttyrd00
- /dev/ttyrd01
BaudRate: 115200
Namespace: c6c45e38-9352-11e2-9103-0026bb56ec92
metadata:
    s.KETIMote:
        SourceName: "KETI Motes"
