svc_base_uri: <svc base uri>
username: <pelican username>
password: <pelican password>
sitename: <pelican site name>
name: <thermostat name>
poll_interval: <status poll interval>
timezone: <IANA timezone> # Must Be Recognized IANA Timezone Format
